[build]
  publish = "public"
  command = "hexo generate"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://oaxrlly.github.io"

[[redirects]]
  from = "https://oxarlly.github.io/*"
  to = "https://www.oxarlly.github.io/:splat"
  status = 301
  force = true