[build]
  publish = "public"
  command = "hexo generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  [[headers."/*"]]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/.netlify/identity/oauth/github"
  to = "/.netlify/identity/oauth/github"
  status = 200
