[build]
  publish = "public"  # Hexo 生成的静态网站的目录
  command = "hexo generate" # Hexo 生成静态网站的命令

[[plugins]]
  package = "./netlify-plugin-decap-hexo-preview.js" # 你的插件/脚本的路径
  [plugins.inputs]
    repoOwner = "oxarlly"
    repoName = "oxarlly/myhexo1"
    branch = "master"
    contentPath = "source" # Decap CMS 内容在仓库中的路径
    hexoSourceDir = "source/_posts" # Hexo 的文章源文件目录
    githubToken = "${GITHUB_TOKEN}" # 从 Netlify 环境变量中获取 GitHub Token
