backend:
  name: github
  repo: oxarlly/myhexo1  # 替换为你的 GitHub 仓库
  branch: master  # 替换为你的分支名称

media_folder: "source/images"  # 媒体文件存放的目录
public_folder: "images"  # 媒体文件对外访问的目录

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"  # 博客文章存放的目录
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {name: "path", label: "Path"}
      - {name: "date", label: "Date", widget: "datetime"}
      - {name: "title", label: "Title"}
      - {name: "body", label: "Body", widget: "markdown"}
